import { index, integer, primaryKey, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', { id:text('id').primaryKey(), email:text('email').notNull(), name:text('name'), createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull() }, (table) => [uniqueIndex('idx_users_email').on(table.email)]);

export const workspaces = sqliteTable('workspaces', { id:text('id').primaryKey(), name:text('name').notNull(), ownerId:text('owner_id').notNull().references(() => users.id), createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(), updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull() }, (table) => [index('idx_workspaces_owner_id').on(table.ownerId)]);

export const workspaceMembers = sqliteTable('workspace_members', { workspaceId:text('workspace_id').notNull().references(() => workspaces.id,{onDelete:'cascade'}), userId:text('user_id').notNull().references(() => users.id,{onDelete:'cascade'}), role:text('role',{enum:['owner','editor','viewer']}).notNull(), createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull() }, (table) => [primaryKey({columns:[table.workspaceId,table.userId]}), index('idx_workspace_members_user_id').on(table.userId)]);

export const files = sqliteTable('files', { id:text('id').primaryKey(), workspaceId:text('workspace_id').notNull().references(() => workspaces.id,{onDelete:'cascade'}), path:text('path').notNull(), kind:text('kind',{enum:['file','directory']}).notNull(), contentType:text('content_type'), size:integer('size').notNull().default(0), currentVersion:integer('current_version').notNull().default(0), createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(), updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull() }, (table) => [uniqueIndex('idx_files_workspace_path').on(table.workspaceId,table.path), index('idx_files_workspace_id').on(table.workspaceId)]);

export const fileVersions = sqliteTable('file_versions', { id:text('id').primaryKey(), fileId:text('file_id').notNull().references(() => files.id,{onDelete:'cascade'}), version:integer('version').notNull(), objectKey:text('object_key').notNull(), size:integer('size').notNull(), createdBy:text('created_by').notNull().references(() => users.id), createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull() }, (table) => [uniqueIndex('idx_file_versions_file_version').on(table.fileId,table.version)]);

export const actions = sqliteTable('actions', { id:text('id').primaryKey(), workspaceId:text('workspace_id').notNull().references(() => workspaces.id,{onDelete:'cascade'}), slug:text('slug').notNull(), name:text('name').notNull(), description:text('description').notNull().default(''), readmePath:text('readme_path'), entrypointPath:text('entrypoint_path').notNull(), viewPath:text('view_path'), createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(), updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull() }, (table) => [uniqueIndex('idx_actions_workspace_slug').on(table.workspaceId,table.slug)]);

export const runs = sqliteTable('runs', { id:text('id').primaryKey(), workspaceId:text('workspace_id').notNull().references(() => workspaces.id,{onDelete:'cascade'}), actionId:text('action_id').notNull().references(() => actions.id,{onDelete:'cascade'}), status:text('status',{enum:['queued','running','succeeded','failed','cancelled']}).notNull(), logs:text('logs').notNull().default(''), errorMessage:text('error_message'), queuedAt:integer('queued_at',{mode:'timestamp_ms'}).notNull(), startedAt:integer('started_at',{mode:'timestamp_ms'}), finishedAt:integer('finished_at',{mode:'timestamp_ms'}) }, (table) => [index('idx_runs_action_queued_at').on(table.actionId,table.queuedAt), index('idx_runs_workspace_status').on(table.workspaceId,table.status)]);
